version: '3'

services:
    node-chatapp:
        build:
            context: ./
            dockerfile: Dockerfile.pro
        ports:
            - 80:3000
        volumes:
            - "./:/app"
            - "/app/node_modules"
